# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1df0558ec6d215ea0d65956e28db9830069a0551efb85a5122e46cbfbac39c9bdffe0dedea47239836e49d54df2699c512a519540f70e589294ce3adc8131dbe

test:
  secret_key_base: 6568a385255ea817bde6e6063fcafa0e664752df3371bb46ca0e4abc95884b3c28ba53923d90578b093f08ff6be23dbedfb88f0a1118f7f128a3e17e5a2b8891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
